name: Warnings

on:
  pull_request_target:
    types: [ "opened", "synchronize", "reopened" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Warning check
      run: |
        printf "Zkompilováno s varováními!\nZvažte nápravu :sob: :sob: :sob: :broken_heart:\n\`\`\`\n" >./warnings

        write_comment() {
            printf "\`\`\`" >> ./warnings
            gh pr comment "${{ github.event.pull_request.number }}" -F "./warnings"
        }

        make -f ./Makefile clean || true
        make -f ./Makefile strict=1 all 2>>./warnings || write_comment

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
